[package]
name = "rust"
version = "0.1.0"
authors = ["Max Cohn <maxc4321@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.1.9"
lazy_static = "1.3.0"